### ISSUE TITLE
Password protected model.

### ISSUE THREAD

**Issue by sardaryannarek** [Shecyy/SAGAN#1]
Hi!
Can I have a password for Your model?

**Comment by Shecyy** [comment]
> Hi! Can I have a password for Your model?

Of course, please provide an email address. I will send the password to your email. @sardaryannarek

**Comment by sardaryannarek** [comment]
Thank You!
nareksardaryann@gmail.com

**Comment by sardaryannarek** [comment]
Dear @Shecyy, Can You review the password? Its not correct for the given archive.
Thank You.

**Comment by LCong1020** [comment]
Dear Shecyy, May I have your model password? Thank you!

**Comment by LCong1020** [comment]
My email address is 1655722607@qq.com
